### ISSUE TITLE
Release version 0.3.0

### ISSUE THREAD

**Issue by cgrdn** [ArgoCanada/bgcArgoDMQC#41]
There are several to-do's/issues that once resolve, would warrant the release of a major version update. This issue will track their status: 

- [x] Argo netCDF file writing, output file must pass Argo FileChecker (#11)
- [x] Retrieving gridded (2D array) variables from an Sprof file, rather than only 1D vectors (#16)
- [ ] Exhaustive formatting and docstrings (#28, which was merged into #39)
- [ ] Dealing with missing PPOX_DOXY variable in traj files for calculating in-air gain (#29)
- [ ] Calculating gain including the carry-over factor (#33)
- [ ] The package has grown and 1000+ line files are impractical, re-organize into folders with more files and \_\_init\_\_.py files (#39)
- [ ] Retrieve optode type before calculating oxygen solubility (#40)

**Comment by cgrdn** [comment]
Closing this issue as it has been replaced with a milestone
